/* DO NOT EDIT!
   This file was automatically generated by m68k-palmos-multigen v2.1
   from IR-Pong2.def  */

	.file	"IR-Pong2-sections.s"

	.globl	__text__
	.lcomm	__text__,4

.text
	.globl	_GccRelocateData
_GccRelocateData:
	bra.w	_GccLoadCodeAndRelocateData

.section ehook
	.long	_GccReleaseCode
