/*
  bt_error.c
*/

#include <PalmOS.h>
#include <BtLib.h>
#include <BtLibTypes.h>

#include "bt_error.h"
#include "Rsc.h"

const err_entry err_entries[] = {
  { btLibErrNoError,                     "btLibErrNoError" },
  { btLibErrError,                       "ErrError"},
  { btLibErrNotOpen,                     "ErrNotOpen"},
  { btLibErrBluetoothOff,                "ErrBluetoothOff"},
  { btLibErrNoPrefs,                     "ErrNoPrefs"},
  { btLibErrAlreadyOpen,                 "ErrAlreadyOpen"},
  { btLibErrOutOfMemory,                 "ErrOutOfMemory"},
  { btLibErrFailed,                      "ErrFailed"},
  { btLibErrInProgress,                  "ErrInProgress"},
  { btLibErrParamError,                  "ErrParamError"},
  { btLibErrTooMany,                     "ErrTooMany"},
  { btLibErrPending,                     "ErrPending"},
  { btLibErrNotInProgress,               "ErrNotInProgress"},
  { btLibErrRadioInitFailed,             "ErrRadioInitFailed"},
  { btLibErrRadioFatal,                  "ErrRadioFatal"},
  { btLibErrRadioInitialized,            "ErrRadioInitialized"},
  { btLibErrRadioSleepWake,              "ErrRadioSleepWake"},
  { btLibErrNoConnection,                "ErrNoConnection"},
  { btLibErrAlreadyRegistered,           "ErrAlreadyRegistered"},
  { btLibErrNoAclLink,                   "ErrNoAclLink"},
  { btLibErrSdpRemoteRecord,             "ErrSdpRemoteRecord"},
  { btLibErrSdpAdvertised,               "ErrSdpAdvertised"},
  { btLibErrSdpFormat,                   "ErrSdpFormat"},
  { btLibErrSdpNotAdvertised,            "ErrSdpNotAdvertised"},
  { btLibErrSdpQueryVersion,             "ErrSdpQueryVersion"},
  { btLibErrSdpQueryHandle,              "ErrSdpQueryHandle"},
  { btLibErrSdpQuerySyntax,              "ErrSdpQuerySyntax"},
  { btLibErrSdpQueryPduSize,             "ErrSdpQueryPduSize"},
  { btLibErrSdpQueryContinuation,        "ErrSdpQueryContinuation"},
  { btLibErrSdpQueryResources,           "ErrSdpQueryResources"},
  { btLibErrSdpQueryDisconnect,          "ErrSdpQueryDisconnect"},
  { btLibErrSdpInvalidResponse,          "ErrSdpInvalidResponse"},
  { btLibErrSdpAttributeNotSet,          "ErrSdpAttributeNotSet"},
  { btLibErrSdpMapped,                   "ErrSdpMapped"},
  { btLibErrSocket,                      "ErrSocket"},
  { btLibErrSocketProtocol,              "ErrSocketProtocol"},
  { btLibErrSocketRole,                  "ErrSocketRole"},
  { btLibErrSocketPsmUnavailable,        "ErrSocketPsmUnavailable"},
  { btLibErrSocketChannelUnavailable,    "ErrSocketChannelUnavailable"},
  { btLibErrSocketUserDisconnect,        "ErrSocketUserDisconnect"},
  { btLibErrCanceled,                    "ErrCanceled"},
  { btLibErrBusy,                        "ErrBusy"},
  { btLibMeStatusUnknownHciCommand,      "MeStatusUnknownHciCommand"},
  { btLibMeStatusNoConnection,           "MeStatusNoConnection"},
  { btLibMeStatusHardwareFailure,	 "MeStatusHardwareFailure"}, 
  { btLibMeStatusPageTimeout,            "MeStatusPageTimeout"},
  { btLibMeStatusAuthenticateFailure,    "MeStatusAuthenticateFailure"},
  { btLibMeStatusMissingKey,             "MeStatusMissingKey"},
  { btLibMeStatusMemoryFull,             "MeStatusMemoryFull"},
  { btLibMeStatusConnnectionTimeout,     "MeStatusConnnectionTimeout"},
  { btLibMeStatusMaxConnections,         "MeStatusMaxConnections"},
  { btLibMeStatusMaxScoConnections,      "MeStatusMaxScoConnections"},
  { btLibMeStatusMaxAclConnections,      "MeStatusMaxAclConnections"},
  { btLibMeStatusCommandDisallowed,      "MeStatusCommandDisallowed"},
  { btLibMeStatusLimitedResources,       "MeStatusLimitedResources"},
  { btLibMeStatusSecurityError,          "MeStatusSecurityError"},
  { btLibMeStatusPersonalDevice,         "MeStatusPersonalDevice"},
  { btLibMeStatusHostTimeout,            "MeStatusHostTimeout"},
  { btLibMeStatusUnsupportedFeature,     "MeStatusUnsupportedFeature"},
  { btLibMeStatusInvalidHciParam,        "MeStatusInvalidHciParam"},
  { btLibMeStatusUserTerminated,         "MeStatusUserTerminated"},
  { btLibMeStatusLowResources,           "MeStatusLowResources"},
  { btLibMeStatusPowerOff,               "MeStatusPowerOff"},
  { btLibMeStatusLocalTerminated,        "MeStatusLocalTerminated"},
  { btLibMeStatusRepeatedAttempts,       "MeStatusRepeatedAttempts"},
  { btLibMeStatusPairingNotAllowed,      "MeStatusPairingNotAllowed"},
  { btLibMeStatusUnknownLmpPDU,          "MeStatusUnknownLmpPDU"},
  { btLibMeStatusUnsupportedRemote,      "MeStatusUnsupportedRemote"},
  { btLibMeStatusScoOffsetRejected,      "MeStatusScoOffsetRejected"},
  { btLibMeStatusScoIntervalRejected,    "MeStatusScoIntervalRejected"},
  { btLibMeStatusScoAirModeRejected,     "MeStatusScoAirModeRejected"},
  { btLibMeStatusInvalidLmpParam,        "MeStatusInvalidLmpParam"},
  { btLibMeStatusUnspecifiedError,       "MeStatusUnspecifiedError"},
  { btLibMeStatusUnsupportedLmpParam,    "MeStatusUnsupportedLmpParam"},
  { btLibMeStatusRoleChangeNotAllowed,   "MeStatusRoleChangeNotAllowed"},
  { btLibMeStatusLmpResponseTimeout,     "MeStatusLmpResponseTimeout"},
  { btLibMeStatusLmpTransdCollision,     "MeStatusLmpTransdCollision"},
  { btLibMeStatusLmpPduNotAllowed,       "MeStatusLmpPduNotAllowed"},
  { btLibL2DiscReasonUnknown,            "L2DiscReasonUnknown"},
  { btLibL2DiscUserRequest,              "L2DiscUserRequest"},
  { btLibL2DiscRequestTimeout,           "L2DiscRequestTimeout"},
  { btLibL2DiscLinkDisc,                 "L2DiscLinkDisc"},
  { btLibL2DiscQosViolation,             "L2DiscQosViolation"},
  { btLibL2DiscSecurityBlock,            "L2DiscSecurityBlock"},
  { btLibL2DiscConnPsmUnsupported,       "L2DiscConnPsmUnsupported"},
  { btLibL2DiscConnSecurityBlock,        "L2DiscConnSecurityBlock"},
  { btLibL2DiscConnNoResources,          "L2DiscConnNoResources"},
  { btLibL2DiscConfigUnacceptable,       "L2DiscConfigUnacceptable"},
  { btLibL2DiscConfigReject,             "L2DiscConfigReject"},
  { btLibL2DiscConfigOptions,            "L2DiscConfigOptions"},
  { btLibServiceShutdownAppUse,          "ServiceShutdownAppUse"},
  { btLibServiceShutdownPowerCycled,     "ServiceShutdownPowerCycled"},
  { btLibServiceShutdownAclDrop,         "ServiceShutdownAclDrop"},
  { btLibServiceShutdownTimeout,         "ServiceShutdownTimeout"},
  { btLibServiceShutdownDetached,        "ServiceShutdownDetached"},
  { btLibErrInUseByService,              "ErrInUseByService"},
  { btLibErrNoPiconet,                   "ErrNoPiconet"},
  { btLibErrRoleChange,                  "ErrRoleChange"},
  { btLibNotYetSupported,                "NotYetSupported"},
  { btLibErrSdpNotMapped,                "ErrSdpNotMapped"},
  { btLibErrAlreadyConnected,            "ErrAlreadyConnected"},
  { -1,                                  "unknown Error"},
};
  
void bt_error(char *msg, Err err) {
  int i = 0;

  while((err_entries[i].err != err)&&(err_entries[i].err != -1))
    i++;
  
  FrmCustomAlert(alt_bt_err, msg, err_entries[i].str, 0);
}
