/* DO NOT EDIT!
   This file was automatically generated by multigen
   from driver.def  */

	.file	"driver-sections.s"

	.globl	__text__
	.lcomm	__text__,4
	.globl	__text__editfns
	.lcomm	__text__editfns,4

	.globl	__code_section_count
	.equ	__code_section_count,2

.text
	.globl	_GccRelocateData
_GccRelocateData:
	bra.w	_GccLoadCodeAndRelocateData

.section ehook
	.long	_GccReleaseCode
